/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Exepciones.*;
import Diseño.*;
import Constructores.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author amyam
 */
public class Reserva extends javax.swing.JFrame {

    /**
     * Creates new form Reserva
     */
    public Reserva() {
        initComponents();
        jdcFecha_Entrada.setMinSelectableDate(new Date());
        jdcFecha_Salida.setMinSelectableDate(new Date());
        jdcFecha_Entrada.setDate(new Date());
        jdcFecha_Salida.setDate(new Date());
    }

    private void LeerReservas(){
                 try {
            FileInputStream fb=new FileInputStream("RESERVAS.OBJ");
            fceR=new ObjectInputStream(fb);
                R=(Reservacion[][]) fceR.readObject();
               
                //Acomodar el index
                for (int i = 0; i < R[CA.getIdCliente()-1].length; i++) {
                    if (R[CA.getIdCliente()-1][i] == null) return;
                    index++;
                }
        } catch (IOException | ClassNotFoundException ex){ 
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdcReserva = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jdcFecha_Entrada = new com.toedter.calendar.JDateChooser();
        jdcFecha_Salida = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblUbi = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jsfHues = new com.toedter.components.JSpinField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/icons8-estrella-32.png"))); // NOI18N
        jPanel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 24));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/icons8-estrella-32.png"))); // NOI18N
        jPanel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 24));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/icons8-estrella-32.png"))); // NOI18N
        jPanel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, 24));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/icons8-estrella-32.png"))); // NOI18N
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 24));

        jButton1.setBackground(new java.awt.Color(155, 172, 228));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Reservar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 112, 54));

        jPanel6.setBackground(new java.awt.Color(44, 56, 96));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Regresar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrar)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen2.jpg"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 290, 158));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen3.jpg"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen4.jpg"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblName.setText("Antojistos Hotel ");
        jPanel5.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel5.setText("Servicios :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 29));

        jdcReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selec.Habitacion", "Indivudual", "Doble", "Premium" }));
        jdcReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdcReservaActionPerformed(evt);
            }
        });
        jPanel5.add(jdcReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        jLabel6.setText("8.5/10 Muy bueno");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel7.setText("Hotel Familiar con alberca y restarurante");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanel5.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 108, 35));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 485, 502, -1));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(3, 4, 20, 10));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen6.jpg"))); // NOI18N
        jPanel7.add(jLabel19);

        jLabel8.setText("Alberca");
        jPanel7.add(jLabel8);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen7.jpg"))); // NOI18N
        jPanel7.add(jLabel17);

        jLabel10.setText("Bar");
        jPanel7.add(jLabel10);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen8.jpg"))); // NOI18N
        jPanel7.add(jLabel20);

        jLabel12.setText("Wifi Gratis");
        jPanel7.add(jLabel12);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen9.jpg"))); // NOI18N
        jPanel7.add(jLabel18);

        jLabel11.setText("Restaurante");
        jPanel7.add(jLabel11);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen10.jpg"))); // NOI18N
        jPanel7.add(jLabel16);

        jLabel9.setText("Estacionamiento Gratuito");
        jPanel7.add(jLabel9);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imghotel/Imagen11.jpg"))); // NOI18N
        jPanel7.add(jLabel15);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Aire Acondicionado");
        jPanel7.add(jLabel14);

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 480, 100));

        jdcFecha_Entrada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcFecha_EntradaPropertyChange(evt);
            }
        });
        jPanel5.add(jdcFecha_Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 140, -1));

        jdcFecha_Salida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcFecha_SalidaPropertyChange(evt);
            }
        });
        jPanel5.add(jdcFecha_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 140, -1));

        jLabel4.setText("Numero de huespedes");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        jLabel26.setText("Fecha de entrada");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel27.setText("Fecha de salida");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        lblUbi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUbi.setForeground(new java.awt.Color(51, 102, 255));
        lblUbi.setText("Cancun Quintana Roo zona Hotelera");
        jPanel5.add(lblUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 389, -1));

        jLabel13.setText("Tipo de Habitacion");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        jsfHues.setValue(1);
        jsfHues.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jsfHuesPropertyChange(evt);
            }
        });
        jPanel5.add(jsfHues, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(614, 614, 614))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Lee el archivo de texto de usuarios

    
    
    //Busca la posicion en la que el arrayCliente y el Cliente actual coinciden

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switch(jdcReserva.getSelectedIndex()){

            case 0:
            showMessageDialog(this, "Selecciona una Habitacion");
            //lbl.setForeground(Color.red);
            jdcReserva.requestFocus();
            return;

        }
        try{
             LocalDate date1 = jdcFecha_Entrada.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        LocalDate date2 = jdcFecha_Salida.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            if (date2.isBefore(date1)) {
        throw new InvalidDateException("La fecha de salida no puede ser antes que   la fecha de entrada.");
    } 
            calcularTotal();
            GuardarReserva();
        this.setVisible(false);
        Pago f1=new Pago();
        f1.setVisible(true);
        f1.setTotal(lblTotal.getText());
        f1.setDesc(lblName.getText());
        }catch (InvalidDateException e){
            showMessageDialog(this,e.getMessage() );
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void GuardarReserva(){
        try{
        String E="", S="", Tipo;
        int personas=0;
        SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault());
        E=f.format(jdcFecha_Entrada.getDate());
        S=f.format(jdcFecha_Salida.getDate());
        personas=jsfHues.getValue();
        Tipo=jdcReserva.getSelectedItem().toString();
        R[CA.getIdCliente()-1][index++]=new Reservacion(E,S,personas,Tipo,Integer.parseInt(lblTotal.getText()));
        //Reemplazar objecto del archivo
            FileOutputStream fb=new FileOutputStream("RESERVAS.OBJ");
            fcsR=new ObjectOutputStream(fb); fcsR.writeObject(R); fcsR.flush();
            showMessageDialog(this, "Cuenta creada con exito", "Excelente", 1);
             this.setVisible(false);
                Mainpage f1=new Mainpage();
                f1.setVisible(true);
           } catch (IOException ex) {
               
           }   
    }
    
    
    
      private void calcularTotal(){
          int resultado=0;  
          int Huespedes=1;
    try{
       LocalDate date1 = jdcFecha_Entrada.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        LocalDate date2 = jdcFecha_Salida.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        if (date2.isBefore(date1)) {
        throw new InvalidDateException("La fecha de salida no puede ser antes que   la fecha de entrada.");
    } 
        long daysDifference = Duration.between(date1.atStartOfDay(), date2.atStartOfDay()).toDays();
      int result = Math.abs((int) daysDifference)+1;
       Huespedes=jsfHues.getValue();
        int Valor=0;
        switch(jdcReserva.getSelectedIndex()){
            case 0:
            Valor=0;
            break;
            case 1:
            Valor=2500;
            break;
            case 2 :
            Valor=5000;
            break;
            case 3 :
            Valor=10000;
        }
                      resultado=Valor*result*Huespedes;
    }                                          
catch ( InvalidDateException | NullPointerException e) { 
    resultado=0;
}
    lblTotal.setText(String.valueOf(resultado));
}
      
      
      
    private void jdcReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdcReservaActionPerformed
 calcularTotal();
    }//GEN-LAST:event_jdcReservaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        Mainpage f1=new Mainpage();
        f1.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jdcFecha_EntradaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcFecha_EntradaPropertyChange
        
        jdcFecha_Salida.setMinSelectableDate(jdcFecha_Entrada.getDate());
        calcularTotal();
    }//GEN-LAST:event_jdcFecha_EntradaPropertyChange

    private void jdcFecha_SalidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcFecha_SalidaPropertyChange

        calcularTotal();
    }//GEN-LAST:event_jdcFecha_SalidaPropertyChange

    private void jsfHuesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jsfHuesPropertyChange
        if(jsfHues.getValue()<1){
            jsfHues.setValue(1);
        }
        calcularTotal();
    }//GEN-LAST:event_jsfHuesPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    //declaracion de FCS para la implemantacion de la persistencia
        //Objetos del proyecto
    
//VARIABLES UTILIZADAS PARA DARLE EL VALOR DEL CLIENTE ACTUAL
    UsuarioCliente CA= new UsuarioCliente();
    Hoteles HA= new Hoteles();
    
    //Para guardar la reservacion basandose en el cliente actaul
    private ObjectOutputStream fcsR;
    private ObjectInputStream fceR;
    Reservacion[][] R= new Reservacion[30][30];
    
    private int index=0, pos=-1;
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jdcFecha_Entrada;
    private com.toedter.calendar.JDateChooser jdcFecha_Salida;
    private javax.swing.JComboBox<String> jdcReserva;
    private com.toedter.components.JSpinField jsfHues;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUbi;
    // End of variables declaration//GEN-END:variables
//METODOS MANDADOS DESDE LA PANTALLA ANTERIOR
//Leer el cliente actual
    public void leerCA(UsuarioCliente c){
        this.CA=c;
        System.out.println(CA.getIdCliente());
        LeerReservas();
    }
    
    public void leerHA(Hoteles h){
        this.HA=h;
        lblName.setText(HA.getNombre());
        lblUbi.setText(HA.getUbicacion());
    }
}
